name: "Combine PRs"

# Controls when the action will run - in this case triggered manually
on:
  workflow_dispatch:
    inputs:
      branchPrefix:
        description: "Branch prefix to find combinable PRs based on"
        required: true
        default: "dependabot"
  pull_request:
    types:
      - opened
    branches: -'dependabot/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # outputs:
  #   fetch-branch-names: ${{steps.fetch-branch-names.outputs.values}}

  # pull_request_target:
  #   - type:
  #       - opened
  #   - branches:
  #       - "dependabot/**"

  # Steps represent a sequence of tasks that will be executed as part of the job
  Component_types:
    runs-on: ubuntu-latest
    steps:
      - name: Update Node Dependencies
        uses: neverendingqs/gh-action-node-update-deps@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # NPM token to use when `npm-registry-*` configs are set
        with:
          bump-version: patch # defaults to not bumping the package version
          commit-message-prefix: fix # defaults 'chore'
          package-manager: yarn # defaults to 'npm'
          git-user-email: myemail@example.com # defaults to '41898282+github-actions[bot]@users.noreply.github.com'
          git-user-name: Test # defaults to 'github-actions[bot]'
          pull-request-labels: "dependencies+component:ui" # defaults to 'dependencies'
          target-version: minor # defaults to 'latest'
