name: "Combine PRs"

# Controls when the action will run - in this case triggered manually
on:
  workflow_dispatch:
    inputs:
      branchPrefix:
        description: "Branch prefix to find combinable PRs based on"
        required: true
        default: "dependabot"
  pull_request:
    types:
      - opened
    branches: -'dependabot/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  combine-prs:
    runs-on: ubuntu-latest
    outputs:
      fetch-branch-names: ${{steps.fetch-branch-names.outputs.values}}

    # pull_request_target:
    #   - type:
    #       - opened
    #   - branches:
    #       - "dependabot/**"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fetch branch names
        id: fetch-branch-names
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pulls = await github.paginate('GET /repos/AlexSCorey/dependabot-test/pulls', {
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            branches = [];
            uiBranches=[]
            apiBranches
            uiPrs = [];
            apiPrs=[];
            base_branch = null;
            for (const pull of pulls) {
              const branch = pull['head']['ref'];
              console.log('Pull for branch: ' + branch);
              if (branch.startsWith('dependabot')) {
                console.log('Branch matched: ' + branch);
                statusOK = true;
                if(${{ github.event.inputs.mustBeGreen }}) {
                  console.log('Checking green status: ' + branch);
                  const statuses = await github.paginate('GET /repos/{owner}/{repo}/commits/{ref}/status', {
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: branch
                  });

                  # if(contains(github.event.pull_request.labels.*.name, 'nocombine')) {
                  #   console.log('Discarding ' + branch + ' with label ' + labelName);
                  #   statusOK = false;
                  # }



                }
                if (statusOK) {
                  if(contains(github.event.pull_request.labels.*.name, 'component:ui')){
                    uiBranches.push(branch)
                    uiPrs.push('#' + pull['number'] + ' ' + pull['title']);
                  }
                  if(contains(github.event.pull_request.labels.*.name, 'component:api')){
                    apiBranches.push(branchui)
                    apiPrs.push('#' + pull['number'] + ' ' + pull['title']);
                  }


                  # console.log('Adding branch to array: ' + branch);
                  # branches.push(branch);
                  # prs.push('#' + pull['number'] + ' ' + pull['title']);
                  # base_branch = pull['base']['ref'];
                }
              }
            }

            if (branches.length == 0) {
              core.setFailed('No PRs/branches matched criteria');
              return;
            }

            # core.setOutput('base-branch', base_branch);
            # core.setOutput('ui_prs-string', uiPrs.join('\n'));
            # core.setOutput('api_prs-string', apiPrs.join('\n'));
            # core.setOutput('prs', prs)

            const uiPrStrings = uiPrs.join('\n')
            const apiPrStrings = apiPrs.join('\n')
            uiCombinedBranches = uiBranches.join(' ')
            apiCombinedBranches = apiBranches.join(' ')
            console.log('Combined: ' + combined);

            core.setOutput('values', [{branches: uiCombinedBranches, prStrings: uiPrStrings, combinedBranchName: UIDependencyUpgrade, label: 'component:ui'}, {branches: apiCombinedBranches, prStrings: apiPrStrings, combinedBranchName: APIDependencyUpgrade, label:'component:api'}])
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  build:
    needs: [combine-prs]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{needs.combine-prs.outputs.values}}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Creates a branch with other PR branches merged together
      - name: Created combined branch
        id: combine-branch-name
        env:
          BASE_BRANCH: devel
          BRANCHES_TO_COMBINE: ${{ matrix.value.branches }}
          COMBINE_BRANCH_NAME: ${{ matrix.value.combinedBranchName}}
        run: |
          echo "$BRANCHES_TO_COMBINE"
          sourcebranches="${BRANCHES_TO_COMBINE%\"}"
          sourcebranches="${sourcebranches#\"}"

          basebranch="${BASE_BRANCH%\"}"
          basebranch="${basebranch#\"}"

          git config pull.rebase false
          git config user.name github-actions
          git config user.email github-actions@github.com

          git branch $COMBINE_BRANCH_NAME $basebranch
          git checkout $COMBINE_BRANCH_NAME
          git pull origin $sourcebranches --no-edit
          git push origin $COMBINE_BRANCH_NAME

      - name: Create Combined Pull Request
        uses: actions/github-script@v3
        env:
          PR_STRINGS: ${{ matrix.value.prStrings }}
          BASE_BRANCH: devel
          COMBINE_BRANCH_NAME: ${{ matrix.value.combinedBranchName}}
          LABEL: ${{ matrix.value.label}}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prString = PR_STRINGS
            const body = 'This PR was created by the Combine PRs action by combining the following PRs:\n' + {{PR_STRINGS}};
            await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Combined PR',
              head: '${{ COMBINE_BRANCH_NAME }}',
              base: '${{ BASE_BRANCH }}',
              body: body
              labels:[${{ LABEL }}]
            });
      # - name: Close PRs that were combined
      #   run: |
      #     for (const pr of '${{ steps.fetch-branch-names.outputs.prs}}') {
      #       console.log(pr)
