---
name: Customize PR body 1
on:
  pull_request:
    types: [labeled, opened, reopened]
jobs:
  pr-check:
    name: Scan PR description for semantic versioning keywords
    if:  contains(github.event.pull_request.labels.*.name, 'dependencies') && contains(github.event.pull_request.labels.*.name, 'component:ui')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      # - name: Read Event (event)
      #   run: echo '${{ toJSON(github.event.pull_request.labels.*.name) }}'

      # - name: Read label dependency
      #   if:  contains(github.event.pull_request.labels.*.name, 'dependencies')
      #   run: echo 'has Dependencies'

      # - name: Read label UI
      #   if:  contains(github.event.pull_request.labels.*.name, 'component:ui')
      #   run: echo 'has UI'

      - name: Check for exactly 2 labels
        env:
            GITHUB_TOKEN: ${{secrets.CUTOM_PR_BODY}}
            OWNER: ${{ github.repository_owner }}
            REPO: ${{ github.event.repository.name }}
            BRANCH: ${{github.event.pull_request.head.ref}}
        run: |
          gh pr checkout ${{ env.BRANCH }}
          gh pr edit --body "Bug, Docs Fix or other nominal change"

