---
name: Customize PR body 1
on:
  pull_request:
    types: [labeled, opened, reopened]
jobs:
  pr-check:
    name: Scan PR description for semantic versioning keywords
    # if: github.event.pull_request.label.name == 'dependencies'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Read Event (event)
        run: echo '${{ toJSON(github.event.pull_request.labels.*.name) }}'

      - name: Read label dependency
        if:  contains(github.event.pull_request.labels.*.name, 'dependencies')
        run: echo 'has Dependencies'

      - name: Read label UI
        if:  contains(github.event.pull_request.labels.*.name, 'component:ui')
        run: echo 'has UI'

      # - name: Read Labels (labels)
      #   run: echo '${{ toJSON(github.labels) }}'

      # - name: Write PR labels to a file
      #   run: |
      #     cat >> pr.labels << __SOME_RANDOM_PR_EOF__
      #     ${{ github.event.pull_request.labels }}
      #     __SOME_RANDOM_PR_EOF__

      # - name: Display the received body for troubleshooting
      #   run: cat pr.labels

      # - name: Check for each of the lines
      #   run: |
      #     grep "dependencies" pr.labels > Z
      #     grep "component:ui" pr.labels > Y
      #     exit 0
      #   shell: bash {0}
      - name: Check for exactly 2 labels
        env:
            GITHUB_TOKEN: ${{secrets.CUTOM_PR_BODY}}
            OWNER: ${{ github.repository_owner }}
            REPO: ${{ github.event.repository.name }}
        run:  gh pr edit --body "Bug, Docs Fix or other nominal change"

