name: Label Combined Dependency PRs
on:
  pull_request:
    types:
      - opened
jobs:
  run_if:
    if: github.head_ref == 'UIDependencyBumpCreatedbyDependbot'
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/pr_labeler.yml
